### ISSUE TITLE
not working - greasemonkey 

### ISSUE THREAD

**Issue by waelhaydar** [zimnicky/VK-free-stickers#1]
installed, nothing shows up...

**Comment by zimnicky** [comment]
Hello, this code is UI specific. VK changed interface about a year ago, so it doesn't work anymore and I'm not planning to fix it. The idea is very simple, so you can write your own version. I think it will be easier than adapt current one to the new interface.

**Comment by waelhaydar** [comment]
remove the code..... or at least keep a not!!!
